spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: http://localhost:8081
          predicates:
            - Path=/api/accounts/**

        - id: task
          uri: http://localhost:8082
          predicates:
            - Path=/api/projects/**

server:
  port: 8079


